# -*- coding: utf-8 -*-
"""EDA on Retails.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pcQ1rVd9pXvVZ_3y38ZPYaOzZfjTDugj
"""

import pandas as pd
data=pd.read_csv('/content/SampleSuperstore.csv')

data=pd.DataFrame(data)

data.head()

data.columns

len(data)

import matplotlib.pyplot as plt
import seaborn as sns

data.drop('Country',axis=1)         #we will drop the column Country because it contains same data

"""Checking if there is any null values in dataset"""

data.isnull().sum()

"""Checking for duplicate values"""

data.duplicated().sum()

"""Removing the duplicate values"""

data.drop_duplicates()

"""Information on data"""

data.info()

"""Statistical Analysis of Dataset"""

data.describe()

plt.bar(data['Ship Mode'],data['Profit'])

plt.bar(data['Region'],data['Profit'])

plt.bar(data['Category'],data['Profit'])

plt.bar(data['Category'],data['Quantity'])

sns.barplot(x='Region',y='Profit',hue='Segment',data=data)

print(data['Sub-Category'].value_counts())
sns.countplot(data['Sub-Category'])
plt.xticks(rotation=90)

"""Heatmap of the Dataset correlation"""

fig,ax=plt.subplots()
sns.heatmap(data.corr(),annot=True)

"""Heatmap of the Data Covariance"""

fig,ax=plt.subplots()
sns.heatmap(data.cov(),annot=True)

sns.countplot(data['Segment'])

sns.countplot(data['Region'])

sns.barplot(data['Sub-Category'],data['Profit'])
plt.xticks(rotation=90)
plt.show()

sns.lineplot('Discount','Profit',data=data,color='b',label='Discount')

data.hist(bins=50,figsize=(20,15))

figsize=(15,10)
sns.pairplot(data,hue='Sub-Category')

"""We will group by some features"""

group_data=pd.DataFrame(data.groupby(['Ship Mode','Segment','Category','Sub-Category','State','Region'])['Quantity','Discount','Sales','Profit'].sum().reset_index())
group_data

"""sum,mean,median,variance....of each state"""

data.groupby('State').Profit.agg(['sum','mean','min','max','var','median','count','std'])

